unstable_features = true
#indent_style = "Visual"
wrap_comments = true
format_strings = true
format_macro_matchers = true
merge_imports = true
max_width = 80
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
struct_field_align_threshold = 40
spaces_around_ranges = true
tab_spaces = 2
edition = "2018"